INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_ENERGY_DETECTION energy_detection)

FIND_PATH(
    ENERGY_DETECTION_INCLUDE_DIRS
    NAMES energy_detection/api.h
    HINTS $ENV{ENERGY_DETECTION_DIR}/include
        ${PC_ENERGY_DETECTION_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    ENERGY_DETECTION_LIBRARIES
    NAMES gnuradio-energy_detection
    HINTS $ENV{ENERGY_DETECTION_DIR}/lib
        ${PC_ENERGY_DETECTION_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ENERGY_DETECTION DEFAULT_MSG ENERGY_DETECTION_LIBRARIES ENERGY_DETECTION_INCLUDE_DIRS)
MARK_AS_ADVANCED(ENERGY_DETECTION_LIBRARIES ENERGY_DETECTION_INCLUDE_DIRS)

